# Generated by Django 3.0.5 on 2023-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Hiểu', 'Hiểu'), ('Biết', 'Biết'), ('Vận dụng thấp', 'Vận dụng thấp'), ('Vận dụng cao', 'Vận dụng cao')], default='Hiểu', max_length=20),
        ),
    ]
