# Generated by Django 3.0.5 on 2023-12-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='biet_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='hieu_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='van_dung_cao_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='van_dung_thap_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
