# Generated by Django 3.0.5 on 2023-12-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20231227_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='biet_marks',
            new_name='biet_number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hieu_marks',
            new_name='hieu_number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='van_dung_cao_marks',
            new_name='van_dung_cao_number',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='van_dung_thap_marks',
            new_name='van_dung_thap_number',
        ),
    ]
