# Generated by Django 3.0.5 on 2023-12-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20231228_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Hiểu', 'hieu'), ('Biết', 'biet'), ('Vận dụng thấp', 'Vận dụng thấp'), ('Vận dụng cao', 'Vận dụng cao')], default='Hiểu', max_length=20),
        ),
    ]
