# Generated by Django 3.0.5 on 2023-12-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20231228_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='biet_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hieu_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='van_dung_cao_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='van_dung_thap_number',
        ),
        migrations.AddField(
            model_name='course',
            name='exam_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('hieu', 'hieu'), ('biet', 'biet'), ('van_dung_thap', 'van_dung_thap'), ('van_dung_cao', 'van_dung_cao')], default='hieu', max_length=20),
        ),
    ]
