# Generated by Django 3.0.5 on 2023-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20231230_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('hieu', 'Hiểu'), ('biet', 'Biết'), ('van_dung_thap', 'Vận dụng thấp'), ('van_dung_cao', 'Vận dụng cao')], default='hieu', max_length=20),
        ),
    ]
