# Generated by Django 3.0.5 on 2023-12-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20231230_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_requirement', models.TextField(verbose_name='Yêu cầu kỳ thi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Course', verbose_name='Khóa học')),
            ],
        ),
    ]
